# Generated by Django 4.1.4 on 2022-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, 'Participant'), (1, 'Staff'), (100, 'Admin')], default=0, verbose_name='Роль')),
                ('last_update_time', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0, verbose_name='Статус заявки')),
                ('result', models.TextField(max_length=500, verbose_name='Результат события')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новое мероприятие', max_length=50, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый этап', max_length=50, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('preview', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Active'), (2, 'Ended')], default=0, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_handler.event')),
                ('users', models.ManyToManyField(through='event_handler.Application', to='user_handler.user')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.TextField(max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Площадка проведения',
                'verbose_name_plural': 'Площадки проведения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_from', to='event_handler.stage')),
                ('stage_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_to', to='event_handler.stage')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_handler.stage'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_handler.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_handler.venue'),
        ),
    ]
